#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: fabric-protos-go
  description: Generated Go bindings for fabric-protos
  homepage: https://hyperledger.github.io/fabric-protos/
  default_branch: main
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
