# SPDX-License-Identifier: Apache-2.0
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
  - automation
# Label to use when marking an issue as stale
staleLabel: stale
only: pulls
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  false
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This repository is maintained by automation, pull requests should be made against
  [hyperledger/fabric-protos](https://github.com/hyperledger/fabric-protos).
