// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/configuration.proto

package peer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AnchorPeers simply represents list of anchor peers which is used in ConfigurationItem
type AnchorPeers struct {
	AnchorPeers          []*AnchorPeer `protobuf:"bytes,1,rep,name=anchor_peers,json=anchorPeers,proto3" json:"anchor_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnchorPeers) Reset()         { *m = AnchorPeers{} }
func (m *AnchorPeers) String() string { return proto.CompactTextString(m) }
func (*AnchorPeers) ProtoMessage()    {}
func (*AnchorPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4978ae8738390a60, []int{0}
}

func (m *AnchorPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeers.Unmarshal(m, b)
}
func (m *AnchorPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeers.Marshal(b, m, deterministic)
}
func (m *AnchorPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeers.Merge(m, src)
}
func (m *AnchorPeers) XXX_Size() int {
	return xxx_messageInfo_AnchorPeers.Size(m)
}
func (m *AnchorPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeers.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeers proto.InternalMessageInfo

func (m *AnchorPeers) GetAnchorPeers() []*AnchorPeer {
	if m != nil {
		return m.AnchorPeers
	}
	return nil
}

// AnchorPeer message structure which provides information about anchor peer, it includes host name,
// port number and peer certificate.
type AnchorPeer struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnchorPeer) Reset()         { *m = AnchorPeer{} }
func (m *AnchorPeer) String() string { return proto.CompactTextString(m) }
func (*AnchorPeer) ProtoMessage()    {}
func (*AnchorPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4978ae8738390a60, []int{1}
}

func (m *AnchorPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeer.Unmarshal(m, b)
}
func (m *AnchorPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeer.Marshal(b, m, deterministic)
}
func (m *AnchorPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeer.Merge(m, src)
}
func (m *AnchorPeer) XXX_Size() int {
	return xxx_messageInfo_AnchorPeer.Size(m)
}
func (m *AnchorPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeer.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeer proto.InternalMessageInfo

func (m *AnchorPeer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AnchorPeer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// APIResource represents an API resource in the peer whose ACL
// is determined by the policy_ref field
type APIResource struct {
	PolicyRef            string   `protobuf:"bytes,1,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResource) Reset()         { *m = APIResource{} }
func (m *APIResource) String() string { return proto.CompactTextString(m) }
func (*APIResource) ProtoMessage()    {}
func (*APIResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_4978ae8738390a60, []int{2}
}

func (m *APIResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResource.Unmarshal(m, b)
}
func (m *APIResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResource.Marshal(b, m, deterministic)
}
func (m *APIResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResource.Merge(m, src)
}
func (m *APIResource) XXX_Size() int {
	return xxx_messageInfo_APIResource.Size(m)
}
func (m *APIResource) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResource.DiscardUnknown(m)
}

var xxx_messageInfo_APIResource proto.InternalMessageInfo

func (m *APIResource) GetPolicyRef() string {
	if m != nil {
		return m.PolicyRef
	}
	return ""
}

// ACLs provides mappings for resources in a channel. APIResource encapsulates
// reference to a policy used to determine ACL for the resource
type ACLs struct {
	Acls                 map[string]*APIResource `protobuf:"bytes,1,rep,name=acls,proto3" json:"acls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ACLs) Reset()         { *m = ACLs{} }
func (m *ACLs) String() string { return proto.CompactTextString(m) }
func (*ACLs) ProtoMessage()    {}
func (*ACLs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4978ae8738390a60, []int{3}
}

func (m *ACLs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLs.Unmarshal(m, b)
}
func (m *ACLs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLs.Marshal(b, m, deterministic)
}
func (m *ACLs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLs.Merge(m, src)
}
func (m *ACLs) XXX_Size() int {
	return xxx_messageInfo_ACLs.Size(m)
}
func (m *ACLs) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLs.DiscardUnknown(m)
}

var xxx_messageInfo_ACLs proto.InternalMessageInfo

func (m *ACLs) GetAcls() map[string]*APIResource {
	if m != nil {
		return m.Acls
	}
	return nil
}

// PrivateDataImplicitCollection stores the configuration for org-specific implicit collections
type PrivateDataImplicitCollection struct {
	MaxPeerCount         int32    `protobuf:"varint,1,opt,name=max_peer_count,json=maxPeerCount,proto3" json:"max_peer_count,omitempty"`
	RequiredPeerCount    int32    `protobuf:"varint,2,opt,name=required_peer_count,json=requiredPeerCount,proto3" json:"required_peer_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateDataImplicitCollection) Reset()         { *m = PrivateDataImplicitCollection{} }
func (m *PrivateDataImplicitCollection) String() string { return proto.CompactTextString(m) }
func (*PrivateDataImplicitCollection) ProtoMessage()    {}
func (*PrivateDataImplicitCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_4978ae8738390a60, []int{4}
}

func (m *PrivateDataImplicitCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateDataImplicitCollection.Unmarshal(m, b)
}
func (m *PrivateDataImplicitCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateDataImplicitCollection.Marshal(b, m, deterministic)
}
func (m *PrivateDataImplicitCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateDataImplicitCollection.Merge(m, src)
}
func (m *PrivateDataImplicitCollection) XXX_Size() int {
	return xxx_messageInfo_PrivateDataImplicitCollection.Size(m)
}
func (m *PrivateDataImplicitCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateDataImplicitCollection.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateDataImplicitCollection proto.InternalMessageInfo

func (m *PrivateDataImplicitCollection) GetMaxPeerCount() int32 {
	if m != nil {
		return m.MaxPeerCount
	}
	return 0
}

func (m *PrivateDataImplicitCollection) GetRequiredPeerCount() int32 {
	if m != nil {
		return m.RequiredPeerCount
	}
	return 0
}

func init() {
	proto.RegisterType((*AnchorPeers)(nil), "protos.AnchorPeers")
	proto.RegisterType((*AnchorPeer)(nil), "protos.AnchorPeer")
	proto.RegisterType((*APIResource)(nil), "protos.APIResource")
	proto.RegisterType((*ACLs)(nil), "protos.ACLs")
	proto.RegisterMapType((map[string]*APIResource)(nil), "protos.ACLs.AclsEntry")
	proto.RegisterType((*PrivateDataImplicitCollection)(nil), "protos.PrivateDataImplicitCollection")
}

func init() { proto.RegisterFile("peer/configuration.proto", fileDescriptor_4978ae8738390a60) }

var fileDescriptor_4978ae8738390a60 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x6b, 0xdc, 0x30,
	0x10, 0x85, 0x71, 0xb2, 0x5b, 0xd8, 0x71, 0x28, 0xad, 0x02, 0x65, 0x29, 0x04, 0x16, 0xd3, 0xc3,
	0xb6, 0x24, 0x36, 0xa4, 0x2d, 0x94, 0xde, 0x5c, 0xa7, 0x87, 0xc0, 0x1e, 0x16, 0x1d, 0x7b, 0x59,
	0xb4, 0xca, 0xd8, 0x16, 0x95, 0x2d, 0x77, 0x24, 0x87, 0xf8, 0xd6, 0x9f, 0x1e, 0x64, 0x65, 0xed,
	0x9c, 0x3c, 0x7e, 0xf3, 0xbd, 0xe1, 0xf1, 0x04, 0xeb, 0x0e, 0x91, 0x32, 0x69, 0xda, 0x52, 0x55,
	0x3d, 0x09, 0xa7, 0x4c, 0x9b, 0x76, 0x64, 0x9c, 0x61, 0x6f, 0xc6, 0x8f, 0x4d, 0xee, 0x20, 0xce,
	0x5b, 0x59, 0x1b, 0xda, 0x23, 0x92, 0x65, 0xdf, 0xe1, 0x42, 0x8c, 0xbf, 0x07, 0xef, 0xb4, 0xeb,
	0x68, 0x73, 0xbe, 0x8d, 0x6f, 0x59, 0x30, 0xd9, 0x74, 0x46, 0x79, 0x2c, 0x66, 0x5b, 0xf2, 0x0d,
	0x60, 0x5e, 0x31, 0x06, 0x8b, 0xda, 0x58, 0xb7, 0x8e, 0x36, 0xd1, 0x76, 0xc5, 0xc7, 0xd9, 0x6b,
	0x9d, 0x21, 0xb7, 0x3e, 0xdb, 0x44, 0xdb, 0x25, 0x1f, 0xe7, 0xe4, 0x1a, 0xe2, 0x7c, 0x7f, 0xcf,
	0xd1, 0x9a, 0x9e, 0x24, 0xb2, 0x2b, 0x80, 0xce, 0x68, 0x25, 0x87, 0x03, 0x61, 0xf9, 0x62, 0x5e,
	0x05, 0x85, 0x63, 0x99, 0xfc, 0x8f, 0x60, 0x91, 0x17, 0x3b, 0xcb, 0xbe, 0xc0, 0x42, 0x48, 0x7d,
	0xca, 0xf6, 0x61, 0xca, 0x56, 0xec, 0x6c, 0x9a, 0x4b, 0x6d, 0x7f, 0xb7, 0x8e, 0x06, 0x3e, 0x32,
	0x1f, 0x77, 0xb0, 0x9a, 0x24, 0xf6, 0x0e, 0xce, 0xff, 0xe2, 0xf0, 0x72, 0xd9, 0x8f, 0xec, 0x33,
	0x2c, 0x1f, 0x85, 0xee, 0x71, 0x8c, 0x15, 0xdf, 0x5e, 0x4e, 0xb7, 0xe6, 0x58, 0x3c, 0x10, 0x3f,
	0xcf, 0x7e, 0x44, 0x49, 0x0f, 0x57, 0x7b, 0x52, 0x8f, 0xc2, 0xe1, 0x9d, 0x70, 0xe2, 0xbe, 0xe9,
	0xb4, 0x92, 0xca, 0x15, 0x46, 0x6b, 0x94, 0xbe, 0x5b, 0xf6, 0x09, 0xde, 0x36, 0xe2, 0x69, 0xec,
	0xee, 0x20, 0x4d, 0xdf, 0x86, 0x0e, 0x96, 0xfc, 0xa2, 0x11, 0x4f, 0xbe, 0x9a, 0xc2, 0x6b, 0x2c,
	0x85, 0x4b, 0xc2, 0x7f, 0xbd, 0x22, 0x7c, 0x78, 0x8d, 0x86, 0x6a, 0xde, 0x9f, 0x56, 0x13, 0xff,
	0x8b, 0x43, 0x62, 0xa8, 0x4a, 0xeb, 0xa1, 0x43, 0xd2, 0xf8, 0x50, 0x21, 0xa5, 0xa5, 0x38, 0x92,
	0x92, 0xa7, 0xb8, 0xfe, 0xc8, 0x9f, 0xeb, 0x4a, 0xb9, 0xba, 0x3f, 0xa6, 0xd2, 0x34, 0xd9, 0x2b,
	0x34, 0x0b, 0xe8, 0x4d, 0x40, 0x6f, 0x2a, 0x93, 0x79, 0xfa, 0x18, 0xde, 0xff, 0xeb, 0x73, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x7b, 0x77, 0x7f, 0x22, 0x02, 0x00, 0x00,
}
