// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/smartbft/configuration.proto

package smartbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Options_Rotation int32

const (
	Options_UNDEFINED Options_Rotation = 0
	Options_OFF       Options_Rotation = 1
	Options_ON        Options_Rotation = 2
)

var Options_Rotation_name = map[int32]string{
	0: "UNDEFINED",
	1: "OFF",
	2: "ON",
}

var Options_Rotation_value = map[string]int32{
	"UNDEFINED": 0,
	"OFF":       1,
	"ON":        2,
}

func (x Options_Rotation) String() string {
	return proto.EnumName(Options_Rotation_name, int32(x))
}

func (Options_Rotation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8a81ac5a2771ff3, []int{2, 0}
}

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "smartbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a81ac5a2771ff3, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	ConsenterId          uint64   `protobuf:"varint,1,opt,name=consenter_id,json=consenterId,proto3" json:"consenter_id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MspId                string   `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	Identity             []byte   `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,6,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,7,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a81ac5a2771ff3, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetConsenterId() uint64 {
	if m != nil {
		return m.ConsenterId
	}
	return 0
}

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetMspId() string {
	if m != nil {
		return m.MspId
	}
	return ""
}

func (m *Consenter) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the smartbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	RequestBatchMaxCount      uint64           `protobuf:"varint,2,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytes      uint64           `protobuf:"varint,3,opt,name=request_batch_max_bytes,json=requestBatchMaxBytes,proto3" json:"request_batch_max_bytes,omitempty"`
	RequestBatchMaxInterval   string           `protobuf:"bytes,4,opt,name=request_batch_max_interval,json=requestBatchMaxInterval,proto3" json:"request_batch_max_interval,omitempty"`
	IncomingMessageBufferSize uint64           `protobuf:"varint,5,opt,name=incoming_message_buffer_size,json=incomingMessageBufferSize,proto3" json:"incoming_message_buffer_size,omitempty"`
	RequestPoolSize           uint64           `protobuf:"varint,6,opt,name=request_pool_size,json=requestPoolSize,proto3" json:"request_pool_size,omitempty"`
	RequestForwardTimeout     string           `protobuf:"bytes,7,opt,name=request_forward_timeout,json=requestForwardTimeout,proto3" json:"request_forward_timeout,omitempty"`
	RequestComplainTimeout    string           `protobuf:"bytes,8,opt,name=request_complain_timeout,json=requestComplainTimeout,proto3" json:"request_complain_timeout,omitempty"`
	RequestAutoRemoveTimeout  string           `protobuf:"bytes,9,opt,name=request_auto_remove_timeout,json=requestAutoRemoveTimeout,proto3" json:"request_auto_remove_timeout,omitempty"`
	ViewChangeResendInterval  string           `protobuf:"bytes,10,opt,name=view_change_resend_interval,json=viewChangeResendInterval,proto3" json:"view_change_resend_interval,omitempty"`
	ViewChangeTimeout         string           `protobuf:"bytes,11,opt,name=view_change_timeout,json=viewChangeTimeout,proto3" json:"view_change_timeout,omitempty"`
	LeaderHeartbeatTimeout    string           `protobuf:"bytes,12,opt,name=leader_heartbeat_timeout,json=leaderHeartbeatTimeout,proto3" json:"leader_heartbeat_timeout,omitempty"`
	LeaderHeartbeatCount      uint64           `protobuf:"varint,13,opt,name=leader_heartbeat_count,json=leaderHeartbeatCount,proto3" json:"leader_heartbeat_count,omitempty"`
	CollectTimeout            string           `protobuf:"bytes,14,opt,name=collect_timeout,json=collectTimeout,proto3" json:"collect_timeout,omitempty"`
	SyncOnStart               bool             `protobuf:"varint,15,opt,name=sync_on_start,json=syncOnStart,proto3" json:"sync_on_start,omitempty"`
	SpeedUpViewChange         bool             `protobuf:"varint,16,opt,name=speed_up_view_change,json=speedUpViewChange,proto3" json:"speed_up_view_change,omitempty"`
	LeaderRotation            Options_Rotation `protobuf:"varint,17,opt,name=leader_rotation,json=leaderRotation,proto3,enum=smartbft.Options_Rotation" json:"leader_rotation,omitempty"`
	DecisionsPerLeader        uint64           `protobuf:"varint,18,opt,name=decisions_per_leader,json=decisionsPerLeader,proto3" json:"decisions_per_leader,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}         `json:"-"`
	XXX_unrecognized          []byte           `json:"-"`
	XXX_sizecache             int32            `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8a81ac5a2771ff3, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetRequestBatchMaxCount() uint64 {
	if m != nil {
		return m.RequestBatchMaxCount
	}
	return 0
}

func (m *Options) GetRequestBatchMaxBytes() uint64 {
	if m != nil {
		return m.RequestBatchMaxBytes
	}
	return 0
}

func (m *Options) GetRequestBatchMaxInterval() string {
	if m != nil {
		return m.RequestBatchMaxInterval
	}
	return ""
}

func (m *Options) GetIncomingMessageBufferSize() uint64 {
	if m != nil {
		return m.IncomingMessageBufferSize
	}
	return 0
}

func (m *Options) GetRequestPoolSize() uint64 {
	if m != nil {
		return m.RequestPoolSize
	}
	return 0
}

func (m *Options) GetRequestForwardTimeout() string {
	if m != nil {
		return m.RequestForwardTimeout
	}
	return ""
}

func (m *Options) GetRequestComplainTimeout() string {
	if m != nil {
		return m.RequestComplainTimeout
	}
	return ""
}

func (m *Options) GetRequestAutoRemoveTimeout() string {
	if m != nil {
		return m.RequestAutoRemoveTimeout
	}
	return ""
}

func (m *Options) GetViewChangeResendInterval() string {
	if m != nil {
		return m.ViewChangeResendInterval
	}
	return ""
}

func (m *Options) GetViewChangeTimeout() string {
	if m != nil {
		return m.ViewChangeTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatTimeout() string {
	if m != nil {
		return m.LeaderHeartbeatTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatCount() uint64 {
	if m != nil {
		return m.LeaderHeartbeatCount
	}
	return 0
}

func (m *Options) GetCollectTimeout() string {
	if m != nil {
		return m.CollectTimeout
	}
	return ""
}

func (m *Options) GetSyncOnStart() bool {
	if m != nil {
		return m.SyncOnStart
	}
	return false
}

func (m *Options) GetSpeedUpViewChange() bool {
	if m != nil {
		return m.SpeedUpViewChange
	}
	return false
}

func (m *Options) GetLeaderRotation() Options_Rotation {
	if m != nil {
		return m.LeaderRotation
	}
	return Options_UNDEFINED
}

func (m *Options) GetDecisionsPerLeader() uint64 {
	if m != nil {
		return m.DecisionsPerLeader
	}
	return 0
}

func init() {
	proto.RegisterEnum("smartbft.Options_Rotation", Options_Rotation_name, Options_Rotation_value)
	proto.RegisterType((*ConfigMetadata)(nil), "smartbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "smartbft.Consenter")
	proto.RegisterType((*Options)(nil), "smartbft.Options")
}

func init() {
	proto.RegisterFile("orderer/smartbft/configuration.proto", fileDescriptor_a8a81ac5a2771ff3)
}

var fileDescriptor_a8a81ac5a2771ff3 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x6f, 0xeb, 0x34,
	0x14, 0xc7, 0x49, 0xd7, 0xdb, 0x1f, 0xee, 0xfa, 0xcb, 0x77, 0xf7, 0x2e, 0x0c, 0x1e, 0x4a, 0x85,
	0xa0, 0x1a, 0x52, 0x8a, 0x36, 0x86, 0x90, 0x10, 0x42, 0xb4, 0x5b, 0x45, 0x11, 0x5b, 0xa7, 0x6c,
	0xe3, 0x81, 0x17, 0xcb, 0x4d, 0x4e, 0x53, 0x4b, 0x49, 0x1c, 0x6c, 0xa7, 0x5b, 0xf7, 0x9f, 0xf2,
	0xc6, 0x9f, 0x82, 0x62, 0x27, 0x69, 0xb5, 0xde, 0xb7, 0xe6, 0x7c, 0xbe, 0x1f, 0x3b, 0xe7, 0x28,
	0x3d, 0xe8, 0x6b, 0x2e, 0x7c, 0x10, 0x20, 0xc6, 0x32, 0xa2, 0x42, 0x2d, 0x57, 0x6a, 0xec, 0xf1,
	0x78, 0xc5, 0x82, 0x54, 0x50, 0xc5, 0x78, 0xec, 0x24, 0x82, 0x2b, 0x8e, 0x1b, 0x05, 0x1d, 0x0a,
	0xd4, 0x99, 0xea, 0xc0, 0x2d, 0x28, 0xea, 0x53, 0x45, 0xf1, 0x25, 0x42, 0x1e, 0x8f, 0x25, 0xc4,
	0x0a, 0x84, 0xb4, 0xad, 0xc1, 0xd1, 0xa8, 0x75, 0xf1, 0xde, 0x29, 0x04, 0x67, 0x5a, 0x30, 0x77,
	0x2f, 0x86, 0xbf, 0x43, 0x75, 0x9e, 0x64, 0x17, 0x48, 0xbb, 0x32, 0xb0, 0x46, 0xad, 0x8b, 0xfe,
	0xce, 0x58, 0x18, 0xe0, 0x16, 0x89, 0xe1, 0xbf, 0x16, 0x6a, 0x96, 0xc7, 0xe0, 0xaf, 0xd0, 0x71,
	0x79, 0x10, 0x61, 0xbe, 0x6d, 0x0d, 0xac, 0x51, 0xd5, 0x6d, 0x95, 0xb5, 0xb9, 0x8f, 0x31, 0xaa,
	0xae, 0xb9, 0x54, 0xfa, 0xe8, 0xa6, 0xab, 0x7f, 0x67, 0xb5, 0x84, 0x0b, 0x65, 0x1f, 0x0d, 0xac,
	0x51, 0xdb, 0xd5, 0xbf, 0xf1, 0x07, 0x54, 0x8b, 0x64, 0x92, 0x1d, 0x52, 0xd5, 0xc9, 0x77, 0x91,
	0x4c, 0xe6, 0x3e, 0x3e, 0x43, 0x0d, 0xe6, 0x43, 0xac, 0x98, 0xda, 0xda, 0xef, 0x06, 0xd6, 0xe8,
	0xd8, 0x2d, 0x9f, 0xf1, 0x37, 0xa8, 0xeb, 0x85, 0x0c, 0x62, 0x45, 0x54, 0x28, 0x89, 0x07, 0x42,
	0xd9, 0x35, 0x1d, 0x69, 0x9b, 0xf2, 0x63, 0x28, 0xa7, 0x20, 0x54, 0x96, 0x93, 0x20, 0x36, 0x20,
	0x76, 0xb9, 0xba, 0xc9, 0x99, 0x72, 0x9e, 0x1b, 0xfe, 0x57, 0x47, 0xf5, 0xbc, 0x61, 0x7c, 0x85,
	0x4e, 0x05, 0xfc, 0x93, 0x82, 0x54, 0x64, 0x49, 0x95, 0xb7, 0x26, 0x11, 0x7d, 0x21, 0x1e, 0x4f,
	0x63, 0xd3, 0x49, 0xd5, 0x3d, 0xc9, 0xf1, 0x24, 0xa3, 0xb7, 0xf4, 0x65, 0x9a, 0xb1, 0x4f, 0x6b,
	0xcb, 0xad, 0x02, 0xa9, 0x9b, 0x3d, 0xd4, 0x26, 0x19, 0xc3, 0x3f, 0xa3, 0xb3, 0x43, 0x8d, 0x65,
	0x13, 0xdc, 0xd0, 0x30, 0x1f, 0xc8, 0xe9, 0x1b, 0x73, 0x9e, 0x63, 0xfc, 0x2b, 0xfa, 0x92, 0xc5,
	0x1e, 0x8f, 0x58, 0x1c, 0x90, 0x08, 0xa4, 0xa4, 0x01, 0x90, 0x65, 0xba, 0x5a, 0x81, 0x20, 0x92,
	0xbd, 0x82, 0x1e, 0x5b, 0xd5, 0xfd, 0xbc, 0xc8, 0xdc, 0x9a, 0xc8, 0x44, 0x27, 0x1e, 0xd8, 0x2b,
	0xe0, 0x73, 0xd4, 0x2f, 0x6e, 0x4f, 0x38, 0x0f, 0x8d, 0x55, 0xd3, 0x56, 0x37, 0x07, 0xf7, 0x9c,
	0x87, 0x3a, 0xfb, 0xe3, 0xae, 0xc1, 0x15, 0x17, 0xcf, 0x54, 0xf8, 0x44, 0xb1, 0x08, 0x78, 0x6a,
	0x66, 0xda, 0x74, 0x3f, 0xe4, 0x78, 0x66, 0xe8, 0xa3, 0x81, 0xf8, 0x27, 0x64, 0x17, 0x9e, 0xc7,
	0xa3, 0x24, 0xa4, 0x2c, 0x2e, 0xc5, 0x86, 0x16, 0x3f, 0xe6, 0x7c, 0x9a, 0xe3, 0xc2, 0xfc, 0x05,
	0x7d, 0x51, 0x98, 0x34, 0x55, 0x9c, 0x08, 0x88, 0xf8, 0x06, 0x4a, 0xb9, 0xa9, 0xe5, 0xe2, 0xf0,
	0xdf, 0x52, 0xc5, 0x5d, 0x1d, 0xd8, 0xd3, 0x37, 0x0c, 0x9e, 0x89, 0xb7, 0xa6, 0x71, 0x00, 0x44,
	0x80, 0x84, 0xd8, 0xdf, 0xcd, 0x16, 0x19, 0x3d, 0x8b, 0x4c, 0x75, 0xc2, 0xd5, 0x81, 0x72, 0xb8,
	0x0e, 0x7a, 0xbf, 0xaf, 0x17, 0xb7, 0xb6, 0xb4, 0xd6, 0xdf, 0x69, 0x7b, 0x7d, 0x86, 0x40, 0x7d,
	0x10, 0x64, 0x0d, 0xd9, 0x7f, 0x08, 0xa8, 0x2a, 0xa5, 0x63, 0xd3, 0xa7, 0xe1, 0xbf, 0x17, 0xb8,
	0x30, 0x7f, 0x40, 0x1f, 0x0f, 0x4c, 0xf3, 0xc1, 0xb5, 0xcd, 0x97, 0xf3, 0xc6, 0x33, 0x1f, 0xdc,
	0xb7, 0xa8, 0xeb, 0xf1, 0x30, 0x04, 0x6f, 0x77, 0x4d, 0x47, 0x5f, 0xd3, 0xc9, 0xcb, 0xc5, 0xf1,
	0x43, 0xd4, 0x96, 0xdb, 0xd8, 0x23, 0x3c, 0x26, 0x52, 0x51, 0xa1, 0xec, 0xee, 0xc0, 0x1a, 0x35,
	0xdc, 0x56, 0x56, 0x5c, 0xc4, 0x0f, 0x59, 0x09, 0x8f, 0xd1, 0x89, 0x4c, 0x00, 0x7c, 0x92, 0x26,
	0x64, 0xaf, 0x6b, 0xbb, 0xa7, 0xa3, 0x7d, 0xcd, 0x9e, 0x92, 0xbf, 0xca, 0xa6, 0xf1, 0x14, 0x75,
	0xf3, 0x77, 0x16, 0x5c, 0xe9, 0x25, 0x65, 0xf7, 0x07, 0xd6, 0xa8, 0x73, 0x71, 0x76, 0xb0, 0x42,
	0x1c, 0x37, 0x4f, 0xb8, 0x1d, 0xa3, 0x14, 0xcf, 0xf8, 0x7b, 0x74, 0xe2, 0x83, 0xc7, 0x64, 0x96,
	0x22, 0x09, 0x08, 0x62, 0xb8, 0x8d, 0x75, 0xdb, 0xb8, 0x64, 0xf7, 0x20, 0xfe, 0xd4, 0x64, 0x78,
	0x8e, 0x1a, 0xa5, 0xdd, 0x46, 0xcd, 0xa7, 0xbb, 0xeb, 0x9b, 0xd9, 0xfc, 0xee, 0xe6, 0xba, 0xf7,
	0x19, 0xae, 0xa3, 0xa3, 0xc5, 0x6c, 0xd6, 0xb3, 0x70, 0x0d, 0x55, 0x16, 0x77, 0xbd, 0xca, 0x1f,
	0xd5, 0x86, 0xd5, 0xab, 0xb8, 0x35, 0xb3, 0x49, 0x27, 0x01, 0x72, 0xb8, 0x08, 0x9c, 0xf5, 0x36,
	0x01, 0x11, 0x82, 0x1f, 0x80, 0x70, 0x56, 0x74, 0x29, 0x98, 0x67, 0x96, 0xab, 0x74, 0xf2, 0x15,
	0x5c, 0xbe, 0xfe, 0xdf, 0x57, 0x01, 0x53, 0xeb, 0x74, 0xe9, 0x78, 0x3c, 0x1a, 0xef, 0x69, 0x63,
	0xa3, 0x8d, 0x8d, 0x36, 0x7e, 0xbb, 0xb9, 0x97, 0x35, 0x0d, 0x2e, 0xff, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0xf9, 0xc3, 0x72, 0x93, 0xd4, 0x05, 0x00, 0x00,
}
